### ISSUE TITLE
Unable to Build

### ISSUE THREAD

**Issue by TheMeq** [Strackeror/PCHex#4]
Hi, I am unable to build the homebrew. I get the following error:

fs.o: In function `_srvGetServiceHandle':
c:/devkitPro/examples/PCHex-master/source/fs.c:17: undefined reference to`srvGetSessionHandle'
collect2.exe: error: ld returned 1 exit status
make[1]: **\* [/c/devkitPro/examples/PCHex-master/PCHex-master.elf] Error 1
make: **\* [build] Error 2

I'm not sure if my environment is set up correctly though :-/

**Comment by Strackeror** [comment]
You need to update your ctrulib, the one from base devkitpro doesn't work

**Comment by TheMeq** [comment]
I'm sure i've done that. I've overwritten the libctru folder with the download from smeagum's github

**Comment by TheMeq** [comment]
I know this is a big ask, but would you be able to help set up my environment? I dunno, remote on my machine and hook me up? I would really like to help with this project, as well as develop other homebrew too. There are no clear instructions on setting up the environment correctly.

**Comment by Strackeror** [comment]
I can't really right now, did you make the library ?

**Comment by TheMeq** [comment]
that would help... let me give that a whirl...

**Comment by TheMeq** [comment]
Yep, got it, ignore me. Thanks
