### ISSUE TITLE
Build Issue

### ISSUE THREAD

**Issue by TheMeq** [Strackeror/PCHex#5]
I have built PKHeX with one minor modification which is unrelated to the error I have been given. 

When running on my 3DS via TubeHax, I get the following:

Init Filesystem...
  Getting save handle
  Initializing save handle
  Opening save archive
  Getting SD Card handle
  Opening SD Card archive
Init FS OK
Loading species data... OK
Loading species names... OK
Loading move names... OK
Loading ability names... OK
Loading item names... OK
Loadind ball names... loading failed : error code - 931117960

**Comment by Strackeror** [comment]
You probably forgot the text_Balls_en.txt
Or didn't put it in the right place

**Comment by TheMeq** [comment]
I think I figured it out, sorry. I was using the export/ files instead of the built files.
