### ISSUE TITLE
Lack of Icon

### ISSUE THREAD

**Issue by TheMeq** [Strackeror/PCHex#6]
Hi, I noticed there was a lack of icon within the build, so, I developed one for you.

Just rename it to PCHex.png (but you already knew that :P)

If you already have one, I apologise, Thanks

![pchex](https://cloud.githubusercontent.com/assets/7303969/9982804/a611d038-5fdf-11e5-89af-5dc6aa604e66.png)

**Comment by Strackeror** [comment]
I did not have one, and I like the style on this one !
I'd prefer it without the 'PCHEX' and 'Strackeror' though, it would be a bit cleaner and simpler

**Comment by TheMeq** [comment]
![pchex](https://cloud.githubusercontent.com/assets/7303969/9982859/bf5d3134-5fe1-11e5-9ec1-fc6d31a150bf.png)

Enjoy ^_^
